In [1]:
import numpy as np


In [3]:
#1차원 배열생성
x1 = np.array([1.0, 2.0,3.0])

x2 = np.array([5.0,10.0,15.0])
print(x1, x2)
print(type(x1), type(x2))

[1. 2. 3.] [ 5. 10. 15.]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [5]:
#2차원 배열생성
y1 = np.array([[1.0, 2.0],[3.0,4.0]])
y2 = np.array([[5.0,10.0],[15.0,20.0]])
print(y1, y2)
print(type(y1), type(y2))

[[1. 2.]
 [3. 4.]] [[ 5. 10.]
 [15. 20.]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
# numpy 원소에 접근 : x1[0] -> 1.0
print(x1[0])
print(y1[0][0])

1.0
1.0


In [8]:
a_list = [1.0, 2.0, 3.0] #리스트를 어레이로 변환
a_np = np.array(a_list)
a_np

array([1., 2., 3.])

In [19]:
#numpy array 생성 #list,array 보다 높은 차원도 가능
arr = np.arange(15)
print(arr.ndim,arr.shape,arr.size)
arr = np.arange(20).reshape(4,5) #reshape(행의갯수, 열의갯수)
print(arr.ndim,arr.shape,arr.size)
arr = np.arange(20).reshape(2,2,5)
print(arr.ndim,arr.shape,arr.size,
     arr.dtype.name, arr.dtype.itemsize)

arr = np.arange(-5,5,0.5).reshape(4,5)
print(arr.ndim,arr.shape,arr.size,
     arr.dtype.name, arr.dtype.itemsize)
arr.reshape(20)

1 (15,) 15
2 (4, 5) 20
3 (2, 2, 5) 20 int32 4
2 (4, 5) 20 float64 8


array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [35]:
#초기화하며 배열 생성 :array
arr = np.empty((4,3)) # 4by3인 배열 생성 ->알 수 없는 값이 들어옴
print(arr)

#초기화하며 배열 생성 :array
arr = np.zeros(5) # 1차원 배열 5행인 배열 초기값은 0
print(arr)
arr = np.zeros((2,3))
arr

#1로 초기화 하면서 배열 생성 메모리에 누적되어있으므로 초기화 해주어야함
arr = np.ones( (3,4) , dtype='i8') #dtype = 'i' 정수로 ,'f' : 실수
print(arr.dtype, arr.dtype.itemsize)

a = np.zeros(5, dtype='U4') #U4 : 문자 문자 크기에 따라 다르게 설정해야함
print(a)
print(a.dtype, a.dtype.itemsize)

arr = np.zeros(3)
print(arr.dtype, arr.dtype.itemsize)

a = np.ones_like(a, dtype='f') #or np.zeros_like(arr)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]
[0. 0. 0. 0. 0.]
int64 8
['' '' '' '' '']
<U4 16
float64 8


In [44]:
# array 연산
x1 = np.array([1.0,2.0,3.0])
y1 = np.array([5.0,10.0,15.0])
x2 = np.array([[1.0,2.0],[3.0,4.0]])
y2 = np.array([[5.0,10.0],[15.0,20.0]])
z1 = np.array([-1.0,-2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

print(x1 + y1)
print(x1 - y1)
print(x1 * y1)
print(x1 / y1)
print(x2 + y2)
print(x2 + z1)
print(x2 * z1)
print(x1 + z2)
print(x1 ** 2)
print(x1 >= 2)
# print(x2 - y2)
# print(x2 * y2)
# print(x2 / y2)

#배열의 형 변환
print(x2.flatten()) #평탄화 시킴 : 모든 차수의 배열을 1차원으로
print(x2.reshape(2,2))

[ 6. 12. 18.]
[ -4.  -8. -12.]
[ 5. 20. 45.]
[0.2 0.2 0.2]
[[ 6. 12.]
 [18. 24.]]
[[0. 0.]
 [2. 2.]]
[[-1. -4.]
 [-3. -8.]]
[[ 6.  7.  8.]
 [11. 12. 13.]
 [16. 17. 18.]]
[1. 4. 9.]
[False  True  True]
[1. 2. 3. 4.]
[[1. 2.]
 [3. 4.]]


In [45]:
print(x2)
print(z1)

[[1. 2.]
 [3. 4.]]
[-1. -2.]


In [50]:
# array 인덱싱, 슬라이싱, 반복
a = np.arange(10)**2
print(a)

print(a[3:5],print(a[2]))
print(a[::-1]) #start:end:-1(step) 뒤에서 부터 출력
a[0:6:2] = -a[0:6:2] #from start to position 6 very element start:end:step
print(a)

#반복문
for x in a:
 print(x+1,end='')
print() 
a = np.arange(1,21,1).reshape(4,5)
print(a) 
print(a[1,1])# 7 
print(a[:2, :])#[행,열]
print(a[1,])
print(a[:,-1])# -는 마지막(행,열)을 의미


[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16] None
[81 64 49 36 25 16  9  4  1  0]
[  0   1  -4   9 -16  25  36  49  64  81]
12-310-152637506582
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
7
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
[ 5 10 15 20]


In [56]:
#numpy의 일반함수
a= np.arange(0,6,1)# array[0,1,2,3,4,5]
print(a) 
print(np.sin(a),np.cos(a)) 

a= np.arange(0.01, 1, 0.05)
print(np.log(a))

a1 = np.array([10,3,4])
a2 = np.array([4,5,6])
print(np.maximum(a1,a2))
print(np.minimum(a1,a2))

[0 1 2 3 4 5]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[-4.60517019 -2.81341072 -2.20727491 -1.83258146 -1.56064775 -1.34707365
 -1.17118298 -1.02165125 -0.89159812 -0.77652879 -0.67334455 -0.5798185
 -0.49429632 -0.41551544 -0.34249031 -0.27443685 -0.21072103 -0.15082289
 -0.09431068 -0.04082199]
[10  5  6]
[4 3 4]


In [61]:
print(np.sum(a1))
np.random.seed() #같은 변수를 저장하고 같은 값을 불러옴
print(np.random.choice(100,5))#0에서 100사이 임의의 5개 숫자
print(np.random.rand(2,3))
print(np.random.randn(2,3))

17
[49 54 58 69 52]
[[0.06541378 0.90381894 0.32575614]
 [0.06210525 0.65961835 0.37429922]]
[[ 0.58656367 -0.99003808 -0.14912287]
 [-0.5611042  -0.13648956 -0.14628453]]


In [69]:
a = np.array([6,1,3,2,4,5])
print(a[np.argmax(a)]) #np.argmax(array) ->가장큰값의 인덱스 반환
print(a[np.argmin(a)])

a = np.array([[0.1,0.8,0.2],[0.3,0.2,0.5],[0.9,0.5,0.3]])
print("===",np.argmax(a, axis=0))
a

6
1
=== [2 0 1]


array([[0.1, 0.8, 0.2],
       [0.3, 0.2, 0.5],
       [0.9, 0.5, 0.3]])

In [80]:
x = np.arange(1,21,1)
print(x[x%3==0])
print(x[x%4==1])
print(x[(x%4==1) & (x%3==0)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
